#! /bin/bash
java -cp lib/antlr4-4.5.3.jar org.antlr.v4.Tool \
    -Werror -visitor -no-listener -o src/main/owl/compiler/ Owl.g4
OWL_TOKENS=src/main/owl/compiler/Owl.tokens
[ -e $OWL_TOKENS ] && rm $OWL_TOKENS src/main/owl/compiler/OwlBaseVisitor.java

