#! /bin/bash

for owl in `find programs -name '*.owl'`; do
    flags=`cat $(dirname "$owl")/FLAGS`
    out=`tempfile`
    err=`tempfile`
    ./owl $flags $owl 1> $out 2> $err
    if [ $? == 0 ]; then
        mv $out $owl.out
    else
        mv $err $owl.err
    fi
done
