#! /bin/bash

for owl in `find programs -name '*.owl'`; do
    out=`tempfile`
    err=`tempfile`
    ./owl --print_ast 1 $owl 1> $out 2> $err
    if [ $? == 0 ]; then
        mv $out $owl.out
    else
        mv $err $owl.err
    fi
done
