#! /bin/bash

for owl in `find programs -name '*.owl'`; do
    flags=`cat $(dirname "$owl")/FLAGS`
    flags=`cat $(dirname "$owl")/FLAGS`
    out=`mktemp`
    echo "--- STDOUT" > $out
    err=`mktemp`
    echo "--- STDERR" > $err
    ./owl $flags $owl 1>> $out 2>> $err
    cat $out $err > ${owl%.owl}.txt
done

