#! /bin/bash

OWL_OUT=.owl_out
CLASS_PATH=`find buck-out/gen -name owl_runtime.jar`:$OWL_OUT
FILE=`python -c "print '$1'.replace('.', '/')"`

javac -d $OWL_OUT -cp $CLASS_PATH "$OWL_OUT/$FILE.java" && java -cp $CLASS_PATH $1
