#! /bin/bash

for owl in `find programs -name '*.owl'`; do
    flags=`cat $(dirname "$owl")/FLAGS`
    out=`mktemp`
    echo "--- STDOUT" > $out
    err=`mktemp`
    echo "--- STDERR" > $err
    ./owl $flags $owl 1>> $out 2>> $err
    cat $out $err > ${owl%.owl}.txt
done
if git status -s programs | grep '\.txt$'; then
    echo 'TESTS FAILED'
else
    echo 'TESTS PASSED'
fi
