#! /bin/bash

ok=1
for owl in `find programs -name '*.owl'`; do
    flags=`cat $(dirname "$owl")/FLAGS`
    out=`tempfile`
    err=`tempfile`
    ./owl $flags $owl 1> $out 2> $err
    if [ $? == 0 ]; then
        diff -ZBu $owl.out $out
        if [ $? != 0 ]; then
            ok=0
        fi
    else
        diff -ZBu $owl.err $err
        if [ $? != 0 ]; then
            ok=0
        fi
    fi
done
if [ $ok == 1 ]; then
    echo 'ALL TESTS PASSED'
fi
