#!/bin/bash
libs=(
    'org/hamcrest/hamcrest-all/1.3/hamcrest-all-1.3.jar'
    'junit/junit/4.12/junit-4.12.jar'
    'org/antlr/antlr4-runtime/4.5.3/antlr4-runtime-4.5.3.jar'
    'org/antlr/antlr4/4.5.3/antlr4-4.5.3.jar'
    'com/beust/jcommander/1.58/jcommander-1.58.jar'
)

for l in "${libs[@]}"; do
    name=$(basename $l)
    [ -e $name ] || curl "http://central.maven.org/maven2/$l" > $name
done
