#! /bin/bash

SRC=compiler/src/main/owl/compiler
java -cp antlr-4.7.2-complete.jar org.antlr.v4.Tool -Werror -visitor -no-listener $SRC/Owl.g4
rm $SRC/Owl*.tokens $SRC/Owl*.interp $SRC/OwlBaseVisitor.java
