#! /bin/bash

CLASS_PATH=`find buck-out/gen -name rt.jar`:owl_out
for owl in `find programs -name '*.owl'`; do
    flags=`cat $(dirname "$owl")/FLAGS`
    out=`mktemp`
    echo "--- STDOUT" > $out
    err=`mktemp`
    echo "--- STDERR" > $err
    ./run $owl $flags 1>> $out 2>> $err
    cat $out $err > ${owl%.owl}.txt
done
if git status -s programs | grep '\.txt$'; then
    echo 'TESTS FAILED'
else
    echo 'TESTS PASSED'
fi
