/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package owl.lang;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AS = 6;
  /** RegularExpression Id. */
  int FN = 7;
  /** RegularExpression Id. */
  int OCT = 20;
  /** RegularExpression Id. */
  int DEC = 21;
  /** RegularExpression Id. */
  int HEX = 22;
  /** RegularExpression Id. */
  int NAME = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "<token of kind 5>",
    "\"as\"",
    "\"fn\"",
    "\".\"",
    "\",\"",
    "\"_\"",
    "\":\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"=>\"",
    "<OCT>",
    "<DEC>",
    "<HEX>",
    "<NAME>",
  };

}
