/* Parser.java */
/* Generated By:JavaCC: Do not edit this line. Parser.java */
package owl.lang;

import java.util.ArrayList;
import java.util.List;

public class Parser implements ParserConstants {

  final public AstModule module() throws ParseException {AstModule module = new AstModule();
    AstFunction f;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FN:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      f = function();
module.addFunction(f);
    }
{if ("" != null) return module;}
    throw new Error("Missing return statement in function");
  }

  final public AstName qualifiedName() throws ParseException {AstName name = new AstName();
    Token tok;
    tok = jj_consume_token(NAME);
name.add(tok.image);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DOT:{
        ;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      jj_consume_token(DOT);
      tok = jj_consume_token(NAME);
name.add(tok.image);
    }
{if ("" != null) return name;}
    throw new Error("Missing return statement in function");
  }

  final public AstFunction function() throws ParseException {AstFunction function = new AstFunction();
    AstVariable a;
    jj_consume_token(FN);
    function.name = jj_consume_token(NAME).image;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LPAREN:{
      jj_consume_token(LPAREN);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NAME:{
        a = variable();
function.args.add(a);
        label_3:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case COMMA:{
            ;
            break;
            }
          default:
            jj_la1[2] = jj_gen;
            break label_3;
          }
          jj_consume_token(COMMA);
          a = variable();
function.args.add(a);
        }
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        ;
      }
      jj_consume_token(RPAREN);
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COLON:{
      jj_consume_token(COLON);
      function.returnType = type();
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    function.block = block();
{if ("" != null) return function;}
    throw new Error("Missing return statement in function");
  }

  final public AstVariable variable() throws ParseException {AstVariable variable = new AstVariable();
    Token tok;
    tok = jj_consume_token(NAME);
variable.name = tok.image;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COLON:{
      jj_consume_token(COLON);
      variable.type = type();
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      ;
    }
{if ("" != null) return variable;}
    throw new Error("Missing return statement in function");
  }

  final public AstBlock block() throws ParseException {AstBlock block = new AstBlock();
    AstNode s;
    jj_consume_token(LCURLY);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SEMICOLON:
      case LPAREN:
      case TILDE:
      case NOT:
      case PLS:
      case MNS:
      case OCT:
      case DEC:
      case HEX:
      case NAME:{
        ;
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        break label_4;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LPAREN:
      case TILDE:
      case NOT:
      case PLS:
      case MNS:
      case OCT:
      case DEC:
      case HEX:
      case NAME:{
        s = statement();
block.statements.add(s);
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        ;
      }
      jj_consume_token(SEMICOLON);
    }
    jj_consume_token(RCURLY);
{if ("" != null) return block;}
    throw new Error("Missing return statement in function");
  }

  final public AstNode prime() throws ParseException {AstNode p = null;
    Token tok;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NAME:{
      p = qualifiedName();
      break;
      }
    case OCT:{
      tok = jj_consume_token(OCT);
p = new AstConstant(tok.image);
      break;
      }
    case DEC:{
      tok = jj_consume_token(DEC);
p = new AstConstant(tok.image);
      break;
      }
    case HEX:{
      tok = jj_consume_token(HEX);
p = new AstConstant(tok.image);
      break;
      }
    case LPAREN:{
      jj_consume_token(LPAREN);
      p = expression();
      jj_consume_token(RPAREN);
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return p;}
    throw new Error("Missing return statement in function");
  }

  final public AstNode call() throws ParseException {AstNode res, arg;
    AstApply apply = null;
    res = prime();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LPAREN:
      case LBRACKET:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_5;
      }
apply = new AstApply();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LPAREN:{
apply.args.add(res);
        jj_consume_token(LPAREN);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LPAREN:
        case TILDE:
        case NOT:
        case PLS:
        case MNS:
        case OCT:
        case DEC:
        case HEX:
        case NAME:{
          arg = expression();
apply.args.add(arg);
          label_6:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case COMMA:{
              ;
              break;
              }
            default:
              jj_la1[11] = jj_gen;
              break label_6;
            }
            jj_consume_token(COMMA);
            arg = expression();
apply.args.add(arg);
          }
          break;
          }
        default:
          jj_la1[12] = jj_gen;
          ;
        }
        jj_consume_token(RPAREN);
        break;
        }
      case LBRACKET:{
apply.args.add(new AstName("[]"));
                apply.args.add(res);
        jj_consume_token(LBRACKET);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LPAREN:
        case TILDE:
        case NOT:
        case PLS:
        case MNS:
        case OCT:
        case DEC:
        case HEX:
        case NAME:{
          arg = expression();
apply.args.add(arg);
          label_7:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case COMMA:{
              ;
              break;
              }
            default:
              jj_la1[13] = jj_gen;
              break label_7;
            }
            jj_consume_token(COMMA);
            arg = expression();
apply.args.add(arg);
          }
          break;
          }
        default:
          jj_la1[14] = jj_gen;
          ;
        }
        jj_consume_token(RBRACKET);
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
res = apply;
    }
{if ("" != null) return res;}
    throw new Error("Missing return statement in function");
  }

  final public AstNode cast() throws ParseException {AstNode res, t;
    res = call();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COLON:{
      jj_consume_token(COLON);
      t = type();
AstApply apply = new AstApply();
            apply.args.add(new AstName(":"));
            apply.args.add(res);
            apply.args.add(t);
            res = apply;
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      ;
    }
{if ("" != null) return res;}
    throw new Error("Missing return statement in function");
  }

  final public AstNode unary() throws ParseException {Token tok = null;
    AstNode n;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TILDE:
    case NOT:
    case PLS:
    case MNS:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TILDE:{
        tok = jj_consume_token(TILDE);
        break;
        }
      case NOT:{
        tok = jj_consume_token(NOT);
        break;
        }
      case PLS:{
        tok = jj_consume_token(PLS);
        break;
        }
      case MNS:{
        tok = jj_consume_token(MNS);
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      ;
    }
    n = cast();
if (tok == null) {
            {if ("" != null) return n;}
        }
        AstApply apply = new AstApply();
        apply.args.add(new AstName(tok.image));
        apply.args.add(n);
        {if ("" != null) return apply;}
    throw new Error("Missing return statement in function");
  }

  final public AstNode expression() throws ParseException {AstNode n;
    n = unary();
{if ("" != null) return n;}
    throw new Error("Missing return statement in function");
  }

  final public AstNode statement() throws ParseException {AstNode expr;
    expr = expression();
{if ("" != null) return expr;}
    throw new Error("Missing return statement in function");
  }

  final public AstType baseType() throws ParseException {AstType type = new AstType();
    type.name = qualifiedName();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LPAREN:
    case LBRACKET:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LPAREN:{
        jj_consume_token(LPAREN);
        jj_consume_token(RPAREN);
        break;
        }
      case LBRACKET:{
        jj_consume_token(LBRACKET);
        jj_consume_token(RBRACKET);
AstType generic = AstType.fromName("Array");
            generic.args.add(type);
            type = generic;
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      ;
    }
{if ("" != null) return type;}
    throw new Error("Missing return statement in function");
  }

  final public AstType type() throws ParseException {AstType t1, t2;
    List<AstType> ts = null;
    t1 = baseType();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ARROW:{
        ;
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        break label_8;
      }
      jj_consume_token(ARROW);
      t2 = baseType();
if (ts == null) {
                ts = new ArrayList<AstType>();
                ts.add(t1);
            }
            ts.add(t2);
    }
if (ts == null) {
            {if ("" != null) return t1;}
        } else {
            AstType generic = AstType.fromName("Fn");
            generic.args = ts;
            {if ("" != null) return generic;}
        }
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public ParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[22];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x80,0x100,0x200,0x20000000,0x1000,0x400,0x400,0x3d981800,0x3d981000,0x3c001000,0x11000,0x200,0x3d981000,0x200,0x3d981000,0x11000,0x400,0x1980000,0x1980000,0x11000,0x11000,0x2000000,};
   }

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[30];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 22; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 30; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
