/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
// Part of the Owl Programming Language source code.
package owl.lang;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ELIF = 6;
  /** RegularExpression Id. */
  int ELSE = 7;
  /** RegularExpression Id. */
  int FN = 8;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int IS = 10;
  /** RegularExpression Id. */
  int NEW = 11;
  /** RegularExpression Id. */
  int DOT = 12;
  /** RegularExpression Id. */
  int COMMA = 13;
  /** RegularExpression Id. */
  int COLON = 14;
  /** RegularExpression Id. */
  int SEMICOLON = 15;
  /** RegularExpression Id. */
  int LPAREN = 16;
  /** RegularExpression Id. */
  int RPAREN = 17;
  /** RegularExpression Id. */
  int LCURLY = 18;
  /** RegularExpression Id. */
  int RCURLY = 19;
  /** RegularExpression Id. */
  int LBRACKET = 20;
  /** RegularExpression Id. */
  int RBRACKET = 21;
  /** RegularExpression Id. */
  int AT = 22;
  /** RegularExpression Id. */
  int TILDE = 23;
  /** RegularExpression Id. */
  int EXC = 24;
  /** RegularExpression Id. */
  int ASSIGN_MUL = 25;
  /** RegularExpression Id. */
  int MUL = 26;
  /** RegularExpression Id. */
  int ASSIGN_DIV = 27;
  /** RegularExpression Id. */
  int DIV = 28;
  /** RegularExpression Id. */
  int ASSIGN_MOD = 29;
  /** RegularExpression Id. */
  int MOD = 30;
  /** RegularExpression Id. */
  int ASSIGN_PLS = 31;
  /** RegularExpression Id. */
  int PLS = 32;
  /** RegularExpression Id. */
  int ASSIGN_MNS = 33;
  /** RegularExpression Id. */
  int MNS = 34;
  /** RegularExpression Id. */
  int ASSIGN_LSHIFT = 35;
  /** RegularExpression Id. */
  int LSHIFT = 36;
  /** RegularExpression Id. */
  int ASSIGN_RSHIFT = 37;
  /** RegularExpression Id. */
  int RSHIFT = 38;
  /** RegularExpression Id. */
  int SIGNED_RSHIFT = 39;
  /** RegularExpression Id. */
  int ASSIGN_SIGNED_RSHIFT = 40;
  /** RegularExpression Id. */
  int ARROW = 41;
  /** RegularExpression Id. */
  int EQ = 42;
  /** RegularExpression Id. */
  int NE = 43;
  /** RegularExpression Id. */
  int LE = 44;
  /** RegularExpression Id. */
  int LT = 45;
  /** RegularExpression Id. */
  int GE = 46;
  /** RegularExpression Id. */
  int GT = 47;
  /** RegularExpression Id. */
  int AND = 48;
  /** RegularExpression Id. */
  int OR = 49;
  /** RegularExpression Id. */
  int ASSIGN_BIT_AND = 50;
  /** RegularExpression Id. */
  int BIT_AND = 51;
  /** RegularExpression Id. */
  int ASSIGN_BIT_XOR = 52;
  /** RegularExpression Id. */
  int BIT_XOR = 53;
  /** RegularExpression Id. */
  int ASSIGN_BIT_OR = 54;
  /** RegularExpression Id. */
  int BIT_OR = 55;
  /** RegularExpression Id. */
  int ASSIGN = 56;
  /** RegularExpression Id. */
  int OCT = 57;
  /** RegularExpression Id. */
  int DEC = 58;
  /** RegularExpression Id. */
  int HEX = 59;
  /** RegularExpression Id. */
  int NAME = 60;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "<token of kind 5>",
    "\"elif\"",
    "\"else\"",
    "\"fn\"",
    "\"if\"",
    "\"is\"",
    "\"new\"",
    "\".\"",
    "\",\"",
    "\":\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"@\"",
    "\"~\"",
    "\"!\"",
    "\"*=\"",
    "\"*\"",
    "\"/=\"",
    "\"/\"",
    "\"%=\"",
    "\"%\"",
    "\"+=\"",
    "\"+\"",
    "\"-=\"",
    "\"-\"",
    "\"<<=\"",
    "\"<<\"",
    "\">>=\"",
    "\">>\"",
    "\">>>\"",
    "\">>>=\"",
    "\"=>\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\"<\"",
    "\">=\"",
    "\">\"",
    "\"&&\"",
    "\"||\"",
    "\"&=\"",
    "\"&\"",
    "\"^=\"",
    "\"^\"",
    "\"|=\"",
    "\"|\"",
    "\"=\"",
    "<OCT>",
    "<DEC>",
    "<HEX>",
    "<NAME>",
  };

}
